__version__: str

class PipeConnection:
    def __init__(
        self, handle: int, readable: bool = True, writable: bool = True
    ) -> None: ...
    def recv_bytes(self) -> bytes | None: ...
    def send_bytes(
        self, buffer: bytes, offset: int = 0, size: int | None = None
    ) -> None: ...
    def close(self) -> None: ...
    def fileno(self) -> int: ...
    @property
    def readable(self) -> bool: ...
    @property
    def writable(self) -> bool: ...
    @property
    def closed(self) -> bool: ...

def Pipe(duplex: bool = True) -> tuple[PipeConnection, PipeConnection]: ...
